### ISSUE TITLE
Error entering ondsel workspace if logged out but token is valid

### ISSUE THREAD

**Issue by sliptonic** [Ondsel-Development/Ondsel-Lens#13]

**Comment by sliptonic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error entering ondsel workspace if logged out but token is valid](https://trello.com/c/6mtlwSYD/13-error-entering-ondsel-workspace-if-logged-out-but-token-is-valid)

**Comment by pieterhijma** [comment]
I believe this is not applicable any longer, at least from #76.
