### ISSUE TITLE
buttons need tooltips

### ISSUE THREAD

**Issue by sliptonic** [Ondsel-Development/Ondsel-Lens#37]
The sharelink icons need tool tips.  They're mostly self-evident but easy improvement

**Comment by PaddleStroke** [comment]
I'm currently investigating this, but it seems rather difficult to implement because we are using a custom delegate.

![image](https://github.com/Ondsel-Development/Ondsel-Lens/assets/19984177/2afe08c9-94df-4b75-a065-c24ad196ff8c)

**Comment by sliptonic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [buttons need tooltips https://github.com/Ondsel-Development](https://trello.com/c/Dsn75iCe/4-buttons-need-tooltips-https-githubcom-ondsel-development)

**Comment by pieterhijma** [comment]
This has already been fixed some time ago.
