### ISSUE TITLE
Handle case of models without obj

### ISSUE THREAD

**Issue by sliptonic** [Ondsel-Development/Ondsel-Lens#58]

**Comment by sliptonic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Handle case of models without obj	https://github.com/Ondsel-Development/Ondsel-Lens/issues/58](https://trello.com/c/ej16y7Gh/8-handle-case-of-models-without-obj-https-githubcom-ondsel-development-ondsel-lens-issues-58)

**Comment by amrit3701** [comment]
@sliptonic Can you elaborate the ticket detail? Did you mean, explore different ways for loading FreeCAD model to ThreeJS?

**Comment by sliptonic** [comment]
I'm closing it.  I think I was harvesting issues out of old user stories and honestly can't remember the context.  We'll reopen if the need resurfaces.
