### ISSUE TITLE
Some uploaded files are not accessible in the add-on

### ISSUE THREAD

**Issue by prokoudine** [Ondsel-Development/Ondsel-Lens#66]
I have 5 files uploaded to lens.ondsel.com, 3 in June and 2 in August:

![image](https://github.com/Ondsel-Development/Ondsel-Lens/assets/57467/d7c66cd3-f367-4bcf-b9c0-d2801c42af49)

The ones uploaded in June are not listed in the add-on, the ones uploaded in August are listed:

![image](https://github.com/Ondsel-Development/Ondsel-Lens/assets/57467/e76dbf99-77c4-4d17-8741-4daf0ffef4a7)

I can only attribute that to updating the version of the add-on in early August when I tested the patch that included pyjwt code (I no longer use the version of the add-on with that patch).

**Comment by sliptonic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BUG:  Missing files](https://trello.com/c/PcuoVI1T/28-bug-missing-files)

**Comment by sliptonic** [comment]
@amrit3701 @PaddleStroke   Any update here?   I'm seeing the same bug.

**Comment by sliptonic** [comment]
It looks like the bug was introduced with PR 62 in the lens.  Server is correct

**Comment by PaddleStroke** [comment]
I think this is a backward compatibility issue. Can you try deleting the
models on the server and uploading again?

Once we reach public beta ensuring backward compatibility will be very
important.

**Comment by amrit3701** [comment]
I already working on migration script and then you can access missing models.

https://trello.com/c/3T2KCUDH/31-add-migration-script-to-support-models-created-before-file-service

**Comment by sliptonic** [comment]
No.  I'm just missing files.  No errors in the console

**Comment by PaddleStroke** [comment]
@prokoudine @sliptonic can you share your account credentials so that I can test ? I'm poking in the dark now so that's not very efficient

**Comment by amrit3701** [comment]
> No. I'm just missing files. No errors in the console
> But my sample file may not be as complex

@sliptonic 

I saw your production account. The missing files objects were created before [https://github.com/Ondsel-Development/Ondsel-Server/pull/60](https://github.com/Ondsel-Development/Ondsel-Server/pull/60) code.

To support old files objects, I started a new ticket.
[https://trello.com/c/hMSTsA1V/41-migrate-old-file-objects](https://trello.com/c/hMSTsA1V/41-migrate-old-file-objects)

**Comment by amrit3701** [comment]
@prokoudine @sliptonic 

The migration script to support old file objects has been successfully executed. All models that have been uploaded are now also visible on the addon side. Please verify.

**Comment by sliptonic** [comment]
Looks much better.  There are three files showing in the addon that are not on the server.

![image](https://github.com/Ondsel-Development/Ondsel-Lens/assets/538057/06768330-b3cb-4417-a69a-aacf0fafda47)

**Comment by amrit3701** [comment]
Both Ondsel models are fixed, now they are not visible on addon side anymore. For File object None there is no Model object assigned and that's why web dashboard not showing. I am not sure how this File object created (maybe by manually calling from Swagger)
