### ISSUE TITLE
Ondsel ES - Ondsel Lens web links does not work

### ISSUE THREAD

**Issue by BMOE79** [Ondsel-Development/Ondsel-Lens#80]
When in Ondsel ES 2024.1.0 and clicking a web link in Ondsel Lens nothing happens. 
Tested by being logged in to Ondsel Lens and clinking on the user name and then 'Visit Ondsel Lens' as well as as right clicking on the Ondsel.FCStd model and then 'View in Lens'. 

My system Info:
```
user@computer:~$ cat /etc/issue
Ubuntu 22.04.4 LTS \n \l

user@computer:~$ uname -srvp
Linux 5.15.0-97-generic #107-Ubuntu SMP Wed Feb 7 13:26:48 UTC 2024 x86_64
```
Running Ondsel ES from the command line:
```
user@computer:~$ ./Ondsel_ES_2024.1.0.35694-Linux-x86_64.AppImage
Ondsel 2024.1.0, Libs: 2024.1.0R35694 (Git)
© FreeCAD team and Ondsel Inc., 2001-2024
Ondsel ES is based on the FreeCAD project and released under the terms of the LGPL2.1+ License.
Ondsel ES wouldn't be possible without the FreeCAD community.
```

Then when clicking the linkts to 'Visit Ondsel Lens' and 'View in Lens:
```
gio: https://lens.ondsel.com/login: Failed to execute child process “gio-launch-desktop” (No such file or directory)
gio: https://lens.ondsel.com/model/65d39457fafa25daf1562bf3: Failed to execute child process “gio-launch-desktop” (No such file or directory)
```

Dont know if it the right gio but this seems to be my version of gio:
```
user@computer:~$ gio version
2.72.4
```

**Comment by pieterhijma** [comment]
Thank you for reporting. The addon makes use of [Qt Desktop services](https://github.com/Ondsel-Development/Ondsel-Lens/blob/1c8ea32aab37bfcab1963e13bf4a5c77cbcd5a24/WorkspaceView.py#L1417) which is probably the best way to guarantee opening web pages in the default browser.

In your case, I assume that somehow your system attempts to open web pages using `gio-launch-desktop` whereas this is most likely removed in newer versions of GLib. I hope these resources can help you find a general solution:
- [GLib issue](https://gitlab.gnome.org/GNOME/glib/-/issues/2070)
- [Stack Exchange answer](https://unix.stackexchange.com/questions/606809/what-is-gio-launch-desktop-and-why-does-thunderbird-use-it-to-open-links-in-defa)

I hope this helps you to solve the problem. Could you report back if you do?

**Comment by pieterhijma** [comment]
Closing because it was likely due to something beyond the addon. Feel free to reopen if the problem persists and depends on the addon.
