### ISSUE TITLE
Freecad initialization error

### ISSUE THREAD

**Issue by dzid26** [Ondsel-Development/Ondsel-Lens#81]
```19:21:10  During initialization the error "invalid syntax (Workspace.py, line 48)" occurred in C:\Users\dzidm\AppData\Roaming\FreeCAD\Mod\Ondsel-Lens\.\InitGui.py```

**Comment by TansuKumar** [comment]
same problem i tried updating python version aswell

**Comment by desperadoNL** [comment]
Same issue here.
New installation with the latest versions

**Comment by Atlas000101** [comment]
I have the same Issuse. Can anyone help ? 

Code in Workspace.py, line 48: 
            case FileStatus.SERVER_ONLY:
                return "Not downloaded"
            case FileStatus.SERVER_COPY_OUTDATED:
                return "Local copy newer"
            case FileStatus.LOCAL_COPY_OUTDATED:
                return "Lens copy newer"
            case FileStatus.SYNCED:
                return "Synced"
            case FileStatus.UNTRACKED:
                return "Untracked"
            case _:
                logger.error(f"Unknown file status: {self}")
                return "Unknown"

**Comment by pieterhijma** [comment]
This is syntax that is only supported in Python 3.10 and higher. Since Python 3.8 and 3.9 have not reached end-of-life yet, we will create a new version of the Lens Addon in which this is fixed.

**Comment by dzid26** [comment]
So Freecad plugins rely on the system python ?

**Comment by pieterhijma** [comment]
> So Freecad plugins rely on the system python installation?

Not only FreeCAD plugins, but FreeCAD in general, but it depends on the way FreeCAD is installed. In an AppImage, for example, there is a Python distribution and I assume that is going to be 3.10 or higher. If FreeCAD is installed by means of package managers, it typically uses the Python distribution of the system. @adrianinsaval will know all the ins and outs of this.

**Comment by dzid26** [comment]
For some reason updating the Ondsel plugin to latest version was not available. I needed to uninstall it first, restart freecad and install again.  
It seems to work now. 
Thank you
